# Use root/example as user/password credentials
version: '3.1'

services:

  dashboard:
    build: .
    restart: always
    ports:
      - 5173:5173

  miner:
    image: gluwa/creditcoin:latest
    ports:
      - ${PORT}:${PORT}
      - ${RPC_PORT}:${RPC_PORT}
    volumes:
      - /Users/notaturkey/dev/miner/data:/data
    command:
      --validator
      --name creditcoin-miner
      --prometheus-external
      --telemetry-url "wss://telemetry.creditcoin.network/submit/ 0"
      --bootnodes "/dns4/bootnode.creditcoin.network/tcp/30333/p2p/12D3KooWAEgDL126EUFxFfdQKiUhmx3BJPdszQHu9PsYsLCuavhb" "/dns4/bootnode2.creditcoin.network/tcp/30333/p2p/12D3KooWSQye3uN3bZQRRC4oZbpiAZXkP2o5UZh6S8pqyh24bF3k" "/dns4/bootnode3.creditcoin.network/tcp/30333/p2p/12D3KooWFrsEZ2aSfiigAxs6ir2kU6en4BewotyCXPhrJ7T1AzjN"
      --public-addr "/dns4/${IP_ADDRESS}/tcp/${PORT}"
      --chain mainnet
      --mining-key ${KEY}
      --base-path /data
      --port ${PORT}
      --unsafe-rpc-external
      --rpc-port ${RPC_PORT}
